name: Publish Docker image

on: push
  
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && mv freezerlist/freezerlist/backend/target staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1
