name: Create Jar Artifact

on: push
  
jobs:
  build_artifact:
    name: Push Docker image to Docker Hub
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - name: Create dir and move target
        run: mkdir staging/backend && mv backend/target staging/backend
      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1